### ISSUE TITLE
Document backwards-incompatible changes with post-1.0 releases.

### ISSUE THREAD

**Issue by akestner** [jezdez/django-hosts#22]
Seems to be some backwards-incompatible changes made between the 0.6 release and the current one.  I resolved my issues by pinning ```django-hosts==0.6``` in my requirements.txt, but that's clearly not an ideal solution.

**Comment by jezdez** [comment]
Good idea, will mark the things in the changelog that are backward incompatible.

**Comment by akestner** [comment]
Thanks!  Any chance for a migration guide as well?

**Comment by jezdez** [comment]
Hm, no sure if that's needed, the changes aren't that drastic

**Comment by akestner** [comment]
Deal.

**Comment by jezdez** [comment]
Done.
