### ISSUE TITLE
import reverse shadow issue

### ISSUE THREAD

**Issue by lehins** [jezdez/django-hosts#23]
`from django_hosts import reverse` 
imports deprecated module `django_hosts.reverse` instead of most important and actually desired `django_hosts.resolvers.reverse` function, basically module effectively shadows the import currently in `django_hosts.__init__.py`, namely `from django_hosts.resolvers import reverse`.
Considering the fact that `django_hosts.reverse` module will be removed in the next version anyways, nothing needs to be done. This issue is opened simply to record that `from django_hosts import reverse` will not work as desired until next release.

**Comment by jezdez** [comment]
Damn, you're right, I hadn't realized that, one of the things I seem to forget the details of Python's import system. Hmm, I guess I better release the new version sooner ;)

**Comment by jezdez** [comment]
Fixed in 1.2.
